---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check stack directory exists
      ansible.builtin.stat:
        path: /opt/stacks/loki
      register: stack_dir
      failed_when: not stack_dir.stat.exists

    - name: Check compose file exists
      ansible.builtin.stat:
        path: /opt/stacks/loki/compose.yaml
      register: compose_file
      failed_when: not compose_file.stat.exists

    - name: Check loki config exists
      ansible.builtin.stat:
        path: /opt/stacks/loki/loki-config.yml
      register: loki_conf
      failed_when: not loki_conf.stat.exists
