---
- name: Converge
  hosts: all
  become: true
  vars:
    netdata_mode: "child"
    control_node_ip: "192.168.1.1"
    vault_netdata_stream_api_key: "test-api-key-12345"
    target_netdata:
      enabled: true
      version: "stable"
  roles:
    - role: ../../../netdata
