---
# Pin versions compatible with Ansible 2.16.x
collections:
  - name: ansible.posix
    version: ">=1.5.0,<2.0.0"
  - name: community.general
    version: ">=8.0.0,<9.0.0"
  - name: community.docker
    version: ">=3.0.0,<4.0.0"
