---
# DNS Role Handlers

- name: restart dns stack
  community.docker.docker_compose_v2:
    project_src: "{{ dns.stack_dir }}"
    state: restarted

- name: restart netdata
  community.docker.docker_compose_v2:
    project_src: /opt/dockge/stacks/netdata
    state: restarted
  when: netdata.enabled | default(false)
