---
# Smallstep CA handlers

- name: Restart Step CA
  community.docker.docker_compose_v2:
    project_src: "{{ step_ca.data_dir }}"
    state: restarted
  when: step_ca.enabled | default(false)

- name: Update CA certificates
  ansible.builtin.command: update-ca-certificates
  when: ansible_os_family == "Debian"
