---
- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check stack directory exists
      ansible.builtin.stat:
        path: /opt/stacks/authentik
      register: stack_dir
      failed_when: not stack_dir.stat.exists

    - name: Check compose file exists
      ansible.builtin.stat:
        path: /opt/stacks/authentik/compose.yaml
      register: compose_file
      failed_when: not compose_file.stat.exists

    - name: Check env file exists
      ansible.builtin.stat:
        path: /opt/stacks/authentik/.env
      register: env_file
      failed_when: not env_file.stat.exists
