---
- name: Converge
  hosts: all
  become: true
  vars:
    target_domain: "test.local"
    control_node_ip: "192.168.1.1"
    control_grafana:
      enabled: true
      port: 3000
      version: "latest"
      oidc_enabled: false
    vault_control_grafana_password: "test-password"
  roles:
    - role: grafana
