---
- name: Converge
  hosts: all
  become: true
  vars:
    common_upgrade_packages: false
    common_microcode_enabled: false
    common_set_hostname: false
    common_sysctl_tuning: false  # Doesn't work in Docker containers
  roles:
    - role: ../../../common
