---
- name: Converge
  hosts: all
  become: true
  vars:
    target_domain: "test.local"
    control_node_ip: "192.168.1.1"
    control_step_ca:
      enabled: true
      port: 9443
      ca_name: "Test CA"
    vault_step_ca_password: "test-ca-password"
  roles:
    - role: ../../../step_ca
