---
# Restic role handlers

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  become: true

- name: Enable restic backup timer
  ansible.builtin.systemd:
    name: restic-backup.timer
    enabled: true
    state: started
  become: true

- name: Enable restic check timer
  ansible.builtin.systemd:
    name: restic-check.timer
    enabled: true
    state: started
  become: true
