---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Start backup timer
  ansible.builtin.systemd:
    name: restic-backup.timer
    enabled: true
    state: started

- name: Start check timer
  ansible.builtin.systemd:
    name: restic-check.timer
    enabled: true
    state: started

- name: Start verify timer
  ansible.builtin.systemd:
    name: restic-verify.timer
    enabled: true
    state: started
